version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: iyedzairi/tasks-manager:frontend
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tasks_manager_network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: iyedzairi/tasks-manager:backend
    depends_on:
      - database
    networks:
      - tasks_manager_network

  database:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    networks:
      - tasks_manager_network

networks:
  tasks_manager_network:
    driver: bridge
volumes:
  mongodb_data: